### ISSUE TITLE
English version support

### ISSUE THREAD

**Issue by alienchristxv3** [hexstr/FGODailyBonus#10]
so I just did  a random test with current cert ext with the English (US) version file and it did pass and printed the corresponding output, some weeks ago the output was giving errors. So how to make it work with the US version? does it have to be an entire new repo? 7

sorry for any inconvenience and thank you for your hard work

**Comment by nishuoshenme** [comment]
I don't know why it works for US version before, it uses the key from JP version.
https://github.com/nishuoshenme/FGODailyBonus/blob/d32592cc432dc0153a401402ee3750c55859d9f9/CertificateExtractor.cs#L11
```CSharp
byte[] bytes = Encoding.UTF8.GetBytes(CatAndMouseGame.AKEY);
byte[] bytes2 = Encoding.UTF8.GetBytes(CatAndMouseGame.AVEC);
```
You can replace these variations with US version.

**Comment by alienchristxv3** [comment]
i think i didnt explain myself correctly, what im saying is that instead of using file 54cc from JP version I used the english version one instead and this was the output

![image](https://user-images.githubusercontent.com/19959133/167307533-5c6d86f8-a62d-46b1-bb11-6ec7e9e3b03c.png)

so i wonder how to make a daily log with the english server.

**Comment by nishuoshenme** [comment]
You need provide the error message.

**Comment by alienchristxv3** [comment]
im only doing the first steps, i havent put the keys and all that into the secrets since i think will be useless since the script points to .jp and not .us like in the picture i inserted.
